---
  - name: Install NGINX
    apt: pkg={{item}} state=installed update-cache=no
    with_items: 
      - nginx
    sudo_user: root

  - name: Install NGINX site conf file.
    template: src=nginx.global.conf.j2 dest=/etc/nginx/nginx.conf
    register: nginx_sites

  - name: Install NGINX site conf file.
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/pypicloud
    register: nginx_sites
  
  - name: Restart NGINX
    service: name=nginx state=restarted
    sudo_user: root
    when: nginx_sites.changed

